/**
 * App Redux Action Types
 */
export const GET_SOMETHING = "GET_SOMETHING";
export const GET_SOMETHING_FAIL = "GET_SOMETHING_FAIL";
export const GET_SOMETHING_SUCCESS = "GET_SOMETHING_SUCCESS";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";

export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const REMOVE_PRODUCT_FAIL = "REMOVE_PRODUCT_FAIL";
export const REMOVE_PRODUCT_SUCCESS = "REMOVE_PRODUCT_SUCCESS";
